// Constants and configuration
export {
  CDOT_API_BASE,
  CORRIDOR_MILE_MARKERS,
  CORRIDOR_SEGMENTS,
  MAX_REASONABLE_SPEED_MPH,
  VIBE_PENALTIES,
  RELEVANT_WEATHER_SENSORS,
  CAMERA_BASE_URL,
  getSegmentByName,
  getSegmentByJsonName,
  getCameraSnapshotUrl,
} from './constants';

// Zod schemas for validation
export {
  VibeScoreSchema,
  TrendSchema,
  CameraSchema,
  LiveDashboardSchema,
  StatusBufferSchema,
  IncidentNormalizationSchema,
  CdotDestinationSchema,
  CdotIncidentSchema,
  CdotConditionSchema,
  CdotWeatherStationSchema,
  CdotWeatherSensorSchema,
  CorridorSegmentSchema,
  NormalizedIncidentSchema,
  SegmentDisplaySchema,
  SegmentBoundsSchema,
  SegmentDataSourcesSchema,
  SegmentThresholdsSchema,
  SegmentConfigSchema,
  SegmentConfigFileSchema,
} from './schemas';

// TypeScript types
export type {
  LiveDashboard,
  StatusBuffer,
  Camera,
  Trend,
  IncidentNormalization,
  CdotDestination,
  CdotIncident,
  CdotCondition,
  CdotWeatherStation,
  CdotWeatherSensor,
  CorridorSegment,
  NormalizedIncident,
  SegmentDisplay,
  SegmentBounds,
  SegmentDataSources,
  SegmentThresholds,
  SegmentConfig,
  SegmentConfigFile,
  SegmentData,
  VibeInput,
  VibeResult,
  WorkerRunResult,
  IncidentCacheEntry,
} from './types';
